// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elystcnjpyhivrbgwevr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVseXN0Y25qcHloaXZyYmd3ZXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjgzNDIsImV4cCI6MjA1OTQwNDM0Mn0.0YSUCb45Y6XMg4IdBqq3mFbhNTXFWu-RGS-tdfhxtjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);